apiVersion: v1
kind: Secret
metadata:
  name: mypwds
stringData:
  rootUser: "root"
  rootHost: "%"
  rootPassword: {{ .Values.mysql.passwordroot }}
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: {{ .Values.mysql.name }}
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: {{ .Values.mysql.instance }}
  router:
    instances: {{ .Values.mysql.routerinstance }}
  datadirVolumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: {{ .Values.mysql.storage }}
