---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tidb-backup-manager
  annotations:
    # helm deletes the object is present due to above "if not" condition
    # add annotation to keep the object
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/component: tidb-backup-manager
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["*"]
- apiGroups: ["pingcap.com"]
  resources: ["backups", "restores"]
  verbs: ["get", "watch", "list", "update"]
  
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace "tidb-backup-manager") }}
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tidb-backup-manager
  annotations:
    # helm deletes the object is present due to above "if not" condition
    # add annotation to keep the object
    helm.sh/resource-policy: keep

{{- end }}



---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tidb-backup-manager
  annotations:
    # helm deletes the object is present due to above "if not" condition
    # add annotation to keep the object
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/component: tidb-backup-manager
subjects:
- kind: ServiceAccount
  name: tidb-backup-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tidb-backup-manager
