apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: myrabbitmq
spec:
  rabbitmq:
    additionalConfig: |
      default_user={{ .Values.rabbitmq.username }}
      default_pass={{ .Values.rabbitmq.password }}
      loopback_users.guest = false
